### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by wobweger** [weareoutman/clockpicker#141]
I cloned repo today

run `npm install` 
`gulp` delivers an error

```
C:\dat\github\clockpicker>gulp
ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (C:\dat\github\clockpicker\node_modules\natives\index.js:143:24)        
    at Object.req [as require] (C:\dat\github\clockpicker\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\dat\github\clockpicker\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)       
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)

C:\dat\github\clockpicker>
```

please advice how to fix it.

**Comment by Laim** [comment]
Hey, 

This isn't an issue with clock picker, this is an issue with Node and Gulp (I'm assuming you're using both of these)

https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node
